# Generated by Django 3.1.7 on 2021-04-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('user_friendly', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('descr', models.TextField()),
                ('is_course', models.BooleanField(blank=True, default=True, null=True)),
                ('for_beginners', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('day_one', models.CharField(blank=True, max_length=254, null=True)),
                ('day_two', models.CharField(blank=True, max_length=254, null=True)),
                ('day_span', models.CharField(blank=True, max_length=254, null=True)),
                ('time_one', models.CharField(blank=True, max_length=254, null=True)),
                ('time_two', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.category')),
            ],
        ),
    ]
